// Arrangement follows Mason's entrance-to-checkout walkthrough.
// x increases to the visitor's right; the back wall is at negative z.
export const STATIONS = [
  {
    id: "grill",
    title: "Fire Market Grill",
    subtitle: "FRESH OFF THE GRILL",
    x: -7.5,
    z: -8.9,
    width: 5.6,
    yaw: 0,
    visit: [-7.5, -6.4],
    color: "#993e2d",
  },
  {
    id: "corn",
    title: "Sweet Corn",
    subtitle: "A LITTLE GOLDEN GOODNESS",
    x: 0,
    z: -8.9,
    width: 5.6,
    yaw: 0,
    visit: [0, -6.4],
    color: "#bb8b2c",
  },
  {
    id: "sushi",
    title: "Market Sushi",
    subtitle: "ROLLED FRESH DAILY",
    x: 7.5,
    z: -8.9,
    width: 5.6,
    yaw: 0,
    visit: [7.5, -6.4],
    color: "#456b64",
  },
  {
    id: "asian",
    title: "Global Entry",
    subtitle: "ASIAN KITCHEN",
    x: -11.55,
    z: -2.6,
    width: 5.2,
    yaw: Math.PI / 2,
    visit: [-9.1, -2.6],
    color: "#ae572d",
  },
  {
    id: "salad",
    title: "Greens",
    subtitle: "BUILD SOMETHING FRESH",
    x: -2.9,
    z: 0.6,
    width: 5.8,
    yaw: Math.PI / 2,
    visit: [-0.5, 0.6],
    color: "#577049",
  },
  {
    id: "drinks",
    title: "Refresh",
    subtitle: "TAKE A LITTLE BREAK",
    x: 11.55,
    z: -2.6,
    width: 4.6,
    yaw: -Math.PI / 2,
    visit: [9.1, -2.6],
    color: "#4a7184",
  },
  {
    id: "checkout",
    title: "Lilybeth’s Checkout",
    x: -7.6,
    z: 8.7,
    width: 3.4,
    yaw: Math.PI,
    visit: [-7.6, 6.3],
    color: "#8c1515",
  },
];
export const SPAWN = { x: -5.1, z: 10.8, yaw: -0.15 };
